Python_World/pizzeria/pizzeria/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('pizzeria_s.urls', namespace='pizzeria_s')),
]

Python_World/pizzeria/pizzeria_s/urls.py
"""定义pizzeria_s的URL模式"""

from django.conf.urls import url

from . import views

urlpatterns = [
	# 主页
	url(r'^$', views.index, name='index'),
	
	# 显示所有的批萨
	url(r'^pizzas/$', views.pizzas, name='pizzas'),
	
	# 特定主题的批萨配料页面
	url(r'^pizzas/(?P<pizza_id>\d+)/$', views.pizza, name='pizza'),
]

Python_World/pizzeria/pizzeria_s/models.py
from django.db import models

# Create your models here.

class Pizza(models.Model):
	"""披萨店披萨名字类型"""
	text = models.CharField(max_length=200)
	date_added = models.DateTimeField(auto_now_add=True)
	
	def __str__(self):
		"""返回模型的字符串表示"""
		return self.text

class Topping(models.Model):
	"""披萨店的具体配料"""
	Pizza = models.ForeignKey(Pizza)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)
	
	class Meta:
		verbose_name_plural = 'entries'
		
	def __str__(self):
		"""返回模型的字符串表示"""
		return self.text[:50] + '...'

Python_World/pizzeria/pizzeria_s/views.py
from django.shortcuts import render
from .models import Pizza

# Create your views here.

def index(request):
	"""披萨店的主页"""
	return render(request, 'pizzeria_s/index.html')
	
def pizzas(request):
	"""显示所有的主题"""
	pizzas = Pizza.objects.order_by('date_added')
	context = {'pizzas': pizzas}
	return render (request, 'pizzeria_s/pizzas.html', context)
	
def pizza(request, pizza_id):
	"""显示每个批萨及其配料组成"""
	pizza = Pizza.objects.get(id=pizza_id)
	entries = pizza.topping_set.order_by('-date_added')
	context = {'pizza': pizza, 'entries': entries}
	return render(request, 'pizzeria_s/pizza.html', context)

Python_World/pizzeria/pizzeria_s/templates/pizzeria_s/base.html
<p>
	<a href="{% url 'pizzeria_s:index' %}">天天批萨店</a> -
	<a href="{% url 'pizzeria_s:pizzas' %}">批萨类型</a>
</p>

{% block content %}{% endblock content %}

Python_World/pizzeria/pizzeria_s/templates/pizzeria_s/index.html
{% extends 'pizzeria_s/base.html' %}

{% block content %}
<p>欢迎来到本披萨店,本店已开通美团外卖欢迎叫外卖。</p>
{% endblock content %}

Python_World/pizzeria/pizzeria_s/templates/pizzeria_s/pizza.html
{% extends 'pizzeria_s/base.html' %}

{% block content %}

	<p>批萨: {{ pizza }}</p>
	<ul>
	{% for topping in entries %}
		<li>
			<p>{{ topping.date_added|date:'M d, Y H:i' }}</p>
			<P>{{ topping.text|linebreaks }}</P>
		</li>
	{% empty %}
		<li>
			没有其它的批萨配料了.
		</li>
	{% endfor %}
	</ul>
	
{% endblock content %} 

Python_World/pizzeria/pizzeria_s/templates/pizzeria_s/pizzas.html
{% extends 'pizzeria_s/base.html' %}

{% block content %}

	<p>批萨</p>
	
	<ul>
		{% for pizza in pizzas %}
			<li>
				<a href="{% url 'pizzeria_s:pizza' pizza.id %}">{{ pizza }}</a>
			</li>
		{% empty %}
			<li>抱歉，最新的批萨美食还没有上架</li>
		{% endfor %}
	</ul>
	
{% endblock content %}